sudo: required
language: python
dist: trusty
python:
    - "pypy"
    - "2.7"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
    - "nightly" # currently points to 3.6-dev

branches:
    only:
        - master
        - develop
os:
  - linux
matrix:
  fast_finish: true
  allow_failures:
      - python: "3.5-dev"
      - python: "nightly"

# Install system dependencies
before_install:
  # Update System
  - sudo apt-get update -qq

  # Install dependencies
  - apt-get install automake libtool git

  # Fetch sources
  - git clone https://github.com/sass/libsass.git
  - git clone https://github.com/sass/sassc.git libsass/sassc

  # Create configure script
  - (cd libsass && autoreconf --force --install)
  # Create custom makefiles for **shared library**, for more info read:
  # 'Difference between static and shared libraries?' before installing libsass  http://stackoverflow.com/q/2649334/802365
  - (cd libsass && autoreconf --force --install && ./configure --disable-tests --enable-shared --prefix=/usr)

  # Build the library
  - make -C libsass -j5

  # Install the library
  - sudo make -C libsass -j5 install

install:
   - pip install .

before_script:
  # Required for running a test
  - pip install .[tests]

# command to run tests
script:
   - py.test

after_success:
   - coveralls
